# backend/formation/src/main/resources/application-prod.properties
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/s3m_db_formation
spring.datasource.username=s3m_user
spring.datasource.password=s3m_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# ===============================
# JWT SECRET
# ===============================
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=86400000

# ===============================
# CORS (Production)
# ===============================
app.frontend.url=https://ifmia.ma/formation
